obj-$(CONFIG_APPID_MOD) := appid.o
appid-objs :=appidentify.o appidentify_match_rules.o appidentify_dpi_engine.o   \
appidentify_hash_table.o appidentify_id.o appidentify_node.o appidentify_proxy.o\
appprio.o appidentify_mod.o appidentify_flow.o appidentify_netlink.o            \
appidentify_upnp.o appidentify_dns.o appidentify_hardcode.o appidentify_utils.o \
appidentify_port.o appidentify_statistics.o dnsparser/dnsparse.o                \
dnsparser/dnsparse_buffer.o dnsparser/dnsparse_error.o                          \
dnsparser/dnsparse_message.o dnsparser/dnsparse_testsuite.o                     \
appidentify_scene.o appidentify_log.o appidentify_proc.o appidentify_api.o

obj-$(CONFIG_APPID_MOD) += extentions/
