#!/bin/sh

mount -a

# added by yangcaiyong for sysfs
mount -t sysfs /sys /sys
# ended add

/bin/mkdir -m 0777 -p /var/lock
/bin/mkdir -m 0777 -p /var/log
/bin/mkdir -m 0777 -p /var/run
/bin/mkdir -m 0777 -p /var/tmp
/bin/mkdir -m 0777 -p /var/Wireless/RT2860AP
/bin/mkdir -m 0777 -p /var/tmp/wsc_upnp

#for the dirs of samba and ntfs-3g, zjj, 20111129
/bin/mkdir -m 0777 -p /var/usbdisk
/bin/mkdir -m 0777 -p /var/dev
/bin/mkdir -m 0777 -p /var/samba/lib
/bin/mkdir -m 0777 -p /var/samba/private
/bin/mkdir -m 0777 -p /var/samba/var/locks
cp -p /etc/passwd.bak /var/passwd
/bin/mkdir -m 0777 -p /var/3G
#end by zjj

echo 1 > /proc/sys/net/ipv4/ip_forward
echo 1 > /proc/sys/net/ipv4/tcp_syncookies
echo 1 > /proc/sys/net/ipv6/conf/all/forwarding

#krammer add for LAN can't continuous ping to WAN when exchenging the routing mode
#bug1126
echo 3 > /proc/sys/net/netfilter/nf_conntrack_icmp_timeout

echo 0 > /proc/sys/net/ipv4/conf/default/accept_source_route
echo 0 > /proc/sys/net/ipv4/conf/all/accept_source_route

insmod /lib/modules/kmdir/kernel/drivers/scsi/scsi_mod.ko
insmod /lib/modules/kmdir/kernel/drivers/scsi/sd_mod.ko

insmod /lib/modules/kmdir/kernel/drivers/usb/core/usbcore.ko

#for 3g-dongle, add by zjj, 20120521
mount -t usbfs usbfs /proc/bus/usb/

insmod /lib/modules/kmdir/kernel/drivers/usb/host/ehci-hcd.ko
insmod /lib/modules/kmdir/kernel/drivers/usb/host/ohci-hcd.ko
insmod /lib/modules/kmdir/kernel/drivers/usb/storage/usb-storage.ko

insmod /lib/modules/kmdir/kernel/drivers/scsi/scsi_wait_scan.ko

insmod /lib/modules/tcledctrl.ko
insmod /lib/modules/tccicmd.ko

#netfilter modules load
insmod /lib/modules/kmdir/kernel/net/netfilter/nf_conntrack_proto_gre.ko
insmod /lib/modules/kmdir/kernel/net/netfilter/nf_conntrack_pptp.ko
insmod /lib/modules/ipt_STAT.ko

#SIP ALG
insmod /lib/modules/kmdir/kernel/net/netfilter/nf_conntrack_sip.ko
insmod /lib/modules/kmdir/kernel/net/ipv4/netfilter/nf_nat_sip.ko

echo "TCSUPPORT_VOIP"
insmod /lib/modules/pcmdriver_slic.ko

/bin/mkdir -p /var/tmp/osal
insmod /lib/modules/extern_osal_kernel_gpl.ko
insmod /lib/modules/osal_kernel.ko

voip_server &

telnetd

insmod /lib/modules/tc3262gmac.ko
# DMT Driver
insmod /lib/modules/tc3162_dmt.ko
# SAR Driver
insmod /lib/modules/tc3162l2sar.ko

ifconfig eth0 up
ifconfig lo 127.0.0.1 netmask 255.0.0.0

cos &
